services:
  api:
    container_name: evolution_api
    image: evoapicloud/evolution-api:latest
    restart: always
    depends_on:
      - redis
      - db
    ports:
      - "8080:8080"
    env_file:
      - evolution-api/.env
    networks:
      - mwanga-net
    extra_hosts:
      - "host.docker.internal:host-gateway"

  redis:
    container_name: evolution_redis
    image: redis:latest
    restart: always
    networks:
      - mwanga-net

  db:
    container_name: evolution_postgres
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_DB=evolution_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres_pass
    volumes:
      - evolution_postgres_data:/var/lib/postgresql/data
    networks:
      - mwanga-net

networks:
  mwanga-net:
    driver: bridge

volumes:
  evolution_postgres_data:
